export const ENDPOINTS = {
  auth: "/auth",
  muestras: "/muestras",
  variaciones: "/variaciones",
  clientes: "/clientes",
  usuarios: "/usuarios",
  molderias: "/molderias",
  ubicaciones: "/ubicaciones",
  fotos: "/fotos",
  trazabilidades: "/trazabilidades",
  producciones: "/producciones",
  movimientosInventario: "/movimientos-inventario",
  presentaciones: "/presentaciones",
  importacion: "/importacion",
  disenadores: "/disenadores",
};
